### ISSUE TITLE
ur0:tai config.txt not working?

### ISSUE THREAD

**Issue by erfg12** [TheOfficialFloW/update365#3]
Has anyone been able to get plugins working through the ur0:tai/config.txt? I deleted ux0:tai/config.txt

Trying to get StorageMgr.skprx working, but it's not even making the log file which makes me think the plugin isn't loading at all. I'm using their latest compile which says 3.65 compatibility, but nothing is happening.

**Comment by mathieulh** [comment]
Try leaving it on your memory card at mountpoint:tai/config.txt instead. For instance it your memory card is mounted as uma0:/ write to uma0:tai/config.txt

This is because the memory card is still mounted as ux0:/ before the plugin gets loaded.

I believe ur0:tai/config.txt was disabled to prevent possible bricks as enso is permanent on this version.

**Comment by erfg12** [comment]
Just tried, nothing happened.

**Comment by Dimensional** [comment]
Incorrect. Enso has a safety measure in place where you can boot it without loading any config.txt file. The system just loads ux0's config before ur0. Deleting ux0's should have made it work. Since StorageMgr is suppose to be an integrated gamesd plugin that is configurable, I recommend just getting TheFlow's version and use that instead.

**Comment by erfg12** [comment]
@Dimensional I thought PSVSD didn't use the gamesd plugin?

update: Yeah that didn't work.

**Comment by Dimensional** [comment]
Weird, as I'm using TheFlow's gamesd.skprx plugin and it works. Sadly it's not allowing me to load my PSVita MC as uma.

Edit: Did you make sure you included the storage_config.txt?

**Comment by erfg12** [comment]
@Dimensional I'm not using an SD2Vita adapter, I'm using the PSVSD http://psvsd.henkaku.xyz

Yes the text file is present and properly named.

**Comment by Dimensional** [comment]
Hmm. I can't tell if the plugin wasn't properly coded for 3.65, or TheFlow did some customizations to his toolchain for compiling the new version. It's not working for me either. At all. May want to submit this to Celeste instead of TheFlow.

**Comment by dinckelman** [comment]
Everything works fine. The plugin you're trying to use hasnt been compiled for 3.65/67 yet even thought the commits have been pushed. You can use xyz's gamesd plugin to mount sd2vita, or wait until celeste's plugin is ready.

**Comment by erfg12** [comment]
@DinckelMan gamesd plugin is not for PSVSD.

**Comment by apizzamra** [comment]
i had the same problem when trying to install gamesd.skprx through ur0:tai 
after rebooting it always looping on molecule logo
